# Generated by Django 4.2.11 on 2024-04-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cage_finch_cages'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='name',
            field=models.CharField(default='', max_length=12),
        ),
    ]
